name: CI
on:
    pull_request:
        branches:
            - main
    push:
        paths:
            - packages/**
            - rollup.config.js
            - package.json
            - pnpm-lock.yaml
            - .github/workflows/**
    workflow_dispatch:

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - uses: pnpm/action-setup@v2

            - uses: actions/setup-node@v3
              with:
                  node-version: 19
                  cache: 'pnpm'

            - run: pnpm install --frozen-lockfile
            - run: pnpm build
            - name: log dist size
              run: |
                  echo $(du -sh dist | cut -f1)
    lint:
        name: Lint
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - uses: pnpm/action-setup@v2

            - uses: actions/setup-node@v3
              with:
                  node-version: 19
                  cache: 'pnpm'

            - run: pnpm install --frozen-lockfile
            - run: pnpm lint
