name: Release
on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    release:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [macos-latest, ubuntu-latest, windows-latest]

        name: Release
        if: "startsWith(github.event.head_commit.message, '(main) release: ') || github.event_name == 'workflow_dispatch'"
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - uses: pnpm/action-setup@v2

            - uses: actions/setup-node@v3
              with:
                  node-version: 20
                  cache: 'pnpm'

            - run: |
                  node -v
                  npm -v
                  pnpm -v

            - run: pnpm i --frozen-lockfile
              name: Install

            - run: pnpm run build
              name: Build
              env:
                  GITHUB_CLIENT_ID: ${{ secrets.OAUTH_CLIENT_ID }}
                  AI_API_URL: ${{ secrets.AI_API_URL }}
                  AI_API_PASSWORD: ${{ secrets.AI_API_PASSWORD }}

            - run: pnpm make:${{ matrix.os }} --publish always
              name: Make
              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
